#!/bin/bash

DEBUG_LOG_FILE_PATH=$1
DEBUG_LOG_FILE_NAME=$(basename "$DEBUG_LOG_FILE_PATH")
DEBUG_LOG_DIR_PATH=$(dirname "$DEBUG_LOG_FILE_PATH")

shift

docker pull langered/bosh-director-logs-parser
docker run --rm -itv "$DEBUG_LOG_DIR_PATH":/usr/src/bosh-director-logs-parser/logs langered/bosh-director-logs-parser:latest "/usr/src/bosh-director-logs-parser/logs/$DEBUG_LOG_FILE_NAME" "$@"

rm -rf "$DEBUG_LOG_FILE_PATH"_files
open "$DEBUG_LOG_FILE_PATH".html
