#!/bin/bash

set -euo pipefail

DEBUG_LOG_FILE_PATH=$1
DEBUG_LOG_FILE_NAME=$(basename "$DEBUG_LOG_FILE_PATH")
DEBUG_LOG_DIR_PATH="$( cd "$( dirname "$DEBUG_LOG_FILE_PATH" )" >/dev/null 2>&1 && pwd )"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

shift

docker pull langered/bosh-director-logs-parser
echo docker run --rm -it -v "$SCRIPT_DIR":/usr/src/bosh-director-logs-parser -v "$DEBUG_LOG_DIR_PATH":/logs langered/bosh-director-logs-parser:latest "/logs/$DEBUG_LOG_FILE_NAME" "$@"

rm -rf "$DEBUG_LOG_FILE_PATH"_files
open "$DEBUG_LOG_FILE_PATH".html
